# Generated by Django 3.0.4 on 2020-03-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_one", models.CharField(max_length=30)),
                ("user_two", models.CharField(max_length=30)),
            ],
        ),
    ]
