# Generated by Django 3.0.4 on 2020-03-12 21:08

import backend.challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_auto_20200312_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="join_code",
            field=models.CharField(
                default=backend.challenges.models.generate_uuid, max_length=37
            ),
        ),
    ]
