# Generated by Django 3.0.4 on 2020-03-14 01:15

import backend.challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_auto_20200312_2108"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="user_one",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="user_two",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="join_code",
            field=models.CharField(
                default=backend.challenges.models.generate_uuid, max_length=512
            ),
        ),
    ]
